#include <ncbi_pch.hpp>
#include "Exon_params.cpp"
#include "Gnomon_param.cpp"
#include "Gnomon_params.cpp"
#include "Intergenic_params.cpp"
#include "Intron_params.cpp"
#include "Length_distribution_params.cpp"
#include "Markov_chain_array.cpp"
#include "Markov_chain_params.cpp"
