/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * File Description:
 *   This code was generated by application DATATOOL
 *   using the following specifications:
 *   'gnomon.asn'.
 *
 * ATTENTION:
 *   Don't edit or commit this file into CVS as this file will
 *   be overridden (by DATATOOL) without warning!
 * ===========================================================================
 */

// standard includes
#include <ncbi_pch.hpp>
#include <serial/serialimpl.hpp>

// generated includes
#include <algo/gnomon/Intergenic_params.hpp>
#include <algo/gnomon/Length_distribution_params.hpp>
BEGIN_NCBI_SCOPE

BEGIN_objects_SCOPE // namespace ncbi::objects::


// generated classes

void CIntergenic_params_Base::ResetLength(void)
{
    if ( !m_Length ) {
        m_Length.Reset(new TLength());
        return;
    }
    (*m_Length).Reset();
}

void CIntergenic_params_Base::SetLength(CIntergenic_params_Base::TLength& value)
{
    m_Length.Reset(&value);
}

void CIntergenic_params_Base::Reset(void)
{
    ResetInitp();
    ResetTo_single();
    ResetLength();
}

BEGIN_NAMED_BASE_CLASS_INFO("Intergenic-params", CIntergenic_params)
{
    SET_CLASS_MODULE("NCBI-GNOMON");
    ADD_NAMED_STD_MEMBER("initp", m_Initp)->SetSetFlag(MEMBER_PTR(m_set_State[0]));
    ADD_NAMED_STD_MEMBER("to-single", m_To_single)->SetSetFlag(MEMBER_PTR(m_set_State[0]));
    ADD_NAMED_REF_MEMBER("length", m_Length, CLength_distribution_params);
    info->RandomOrder();
}
END_CLASS_INFO

// constructor
CIntergenic_params_Base::CIntergenic_params_Base(void)
    : m_Initp(0), m_To_single(0)
{
    memset(m_set_State,0,sizeof(m_set_State));
    if ( !IsAllocatedInPool() ) {
        ResetLength();
    }
}

// destructor
CIntergenic_params_Base::~CIntergenic_params_Base(void)
{
}



END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE

