/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * File Description:
 *   This code was generated by application DATATOOL
 *   using the following specifications:
 *   'gnomon.asn'.
 *
 * ATTENTION:
 *   Don't edit or commit this file into CVS as this file will
 *   be overridden (by DATATOOL) without warning!
 * ===========================================================================
 */

// standard includes
#include <ncbi_pch.hpp>
#include <serial/serialimpl.hpp>

// generated includes
#include <algo/gnomon/Markov_chain_array.hpp>
#include <algo/gnomon/Markov_chain_params.hpp>
BEGIN_NCBI_SCOPE

BEGIN_objects_SCOPE // namespace ncbi::objects::


// generated classes

void CMarkov_chain_array_Base::ResetMatrix(void)
{
    m_Matrix.clear();
    m_set_State[0] &= ~0x30;
}

void CMarkov_chain_array_Base::Reset(void)
{
    ResetIn_exon();
    ResetIn_intron();
    ResetMatrix();
}

BEGIN_NAMED_BASE_CLASS_INFO("Markov-chain-array", CMarkov_chain_array)
{
    SET_CLASS_MODULE("NCBI-GNOMON");
    ADD_NAMED_STD_MEMBER("in-exon", m_In_exon)->SetSetFlag(MEMBER_PTR(m_set_State[0]));
    ADD_NAMED_STD_MEMBER("in-intron", m_In_intron)->SetSetFlag(MEMBER_PTR(m_set_State[0]));
    ADD_NAMED_MEMBER("matrix", m_Matrix, STL_list, (STL_CRef, (CLASS, (CMarkov_chain_params))))->SetSetFlag(MEMBER_PTR(m_set_State[0]));
    info->RandomOrder();
}
END_CLASS_INFO

// constructor
CMarkov_chain_array_Base::CMarkov_chain_array_Base(void)
    : m_In_exon(0), m_In_intron(0)
{
    memset(m_set_State,0,sizeof(m_set_State));
}

// destructor
CMarkov_chain_array_Base::~CMarkov_chain_array_Base(void)
{
}



END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE

