/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * File Description:
 *   This code was generated by application DATATOOL
 *   using the following specifications:
 *   'elink.dtd'.
 *
 * ATTENTION:
 *   Don't edit or commit this file into CVS as this file will
 *   be overridden (by DATATOOL) without warning!
 * ===========================================================================
 */

// standard includes
#include <ncbi_pch.hpp>
#include <serial/serialimpl.hpp>

// generated includes
#include <objtools/eutils/elink/FirstChars.hpp>
BEGIN_elink_SCOPE // namespace elink::


// generated classes

void CFirstChars_Base::ResetFirstChar(void)
{
    m_FirstChar.clear();
    m_set_State[0] &= ~0x3;
}

void CFirstChars_Base::Reset(void)
{
    ResetFirstChar();
}

BEGIN_NAMED_BASE_CLASS_INFO("FirstChars", CFirstChars)
{
    SET_CLASS_MODULE("elink");
    ADD_NAMED_MEMBER("FirstChar", m_FirstChar, STL_list, (STD, (NCBI_NS_STD::string)))->SetOptional()->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    info->RandomOrder();
}
END_CLASS_INFO

// constructor
CFirstChars_Base::CFirstChars_Base(void)
{
    memset(m_set_State,0,sizeof(m_set_State));
}

// destructor
CFirstChars_Base::~CFirstChars_Base(void)
{
}



END_elink_SCOPE // namespace elink::

