/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * File Description:
 *   This code was generated by application DATATOOL
 *   using the following specifications:
 *   'pepXML.xsd'.
 *
 * ATTENTION:
 *   Don't edit or commit this file into CVS as this file will
 *   be overridden (by DATATOOL) without warning!
 * ===========================================================================
 */

// standard includes
#include <ncbi_pch.hpp>
#include <serial/serialimpl.hpp>

// generated includes
#include <algo/ms/formats/pepxml/Asapratio_lc_heavypeak.hpp>
BEGIN_NCBI_SCOPE

BEGIN_objects_SCOPE // namespace ncbi::objects::


// generated classes

void CAsapratio_lc_heavypeak_Base::C_Attlist::ResetIs_heavy(void)
{
    m_Is_heavy.erase();
    m_set_State[0] &= ~0x30000;
}

void CAsapratio_lc_heavypeak_Base::C_Attlist::Reset(void)
{
    ResetStatus();
    ResetLeft_valley();
    ResetRight_valley();
    ResetBackground();
    ResetArea();
    ResetArea_error();
    ResetTime();
    ResetTime_width();
    ResetIs_heavy();
}

BEGIN_NAMED_CLASS_INFO("", CAsapratio_lc_heavypeak_Base::C_Attlist)
{
    SET_INTERNAL_NAME("asapratio_lc_heavypeak", "Attlist");
    SET_CLASS_MODULE("pepXML");
    ADD_NAMED_STD_MEMBER("status", m_Status)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("left_valley", m_Left_valley)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("right_valley", m_Right_valley)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("background", m_Background)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("area", m_Area)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("area_error", m_Area_error)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("time", m_Time)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("time_width", m_Time_width)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("is_heavy", m_Is_heavy)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    info->SetRandomOrder(true);
}
END_CLASS_INFO

// constructor
CAsapratio_lc_heavypeak_Base::C_Attlist::C_Attlist(void)
    : m_Status(0), m_Left_valley(0), m_Right_valley(0), m_Background(0), m_Area(0), m_Area_error(0), m_Time(0), m_Time_width(0)
{
    memset(m_set_State,0,sizeof(m_set_State));
}

// destructor
CAsapratio_lc_heavypeak_Base::C_Attlist::~C_Attlist(void)
{
}


void CAsapratio_lc_heavypeak_Base::ResetAttlist(void)
{
    if ( !m_Attlist ) {
        m_Attlist.Reset(new TAttlist());
        return;
    }
    (*m_Attlist).Reset();
}

void CAsapratio_lc_heavypeak_Base::SetAttlist(CAsapratio_lc_heavypeak_Base::TAttlist& value)
{
    m_Attlist.Reset(&value);
    SetAsapratio_lc_heavypeak();
}

void CAsapratio_lc_heavypeak_Base::Reset(void)
{
    ResetAttlist();
    ResetAsapratio_lc_heavypeak();
}

BEGIN_NAMED_BASE_CLASS_INFO("asapratio_lc_heavypeak", CAsapratio_lc_heavypeak)
{
    SET_CLASS_MODULE("pepXML");
    SET_NAMESPACE("http://regis-web.systemsbiology.net/pepXML")->SetNsQualified(true);
    ADD_NAMED_REF_MEMBER("Attlist", m_Attlist, C_Attlist)->SetNoPrefix()->SetAttlist();
    ADD_NAMED_NULL_MEMBER("asapratio_lc_heavypeak", null, ())->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix()->SetNotag();
    info->RandomOrder();
}
END_CLASS_INFO

// constructor
CAsapratio_lc_heavypeak_Base::CAsapratio_lc_heavypeak_Base(void)
{
    memset(m_set_State,0,sizeof(m_set_State));
    if ( !IsAllocatedInPool() ) {
        ResetAttlist();
    }
}

// destructor
CAsapratio_lc_heavypeak_Base::~CAsapratio_lc_heavypeak_Base(void)
{
}



END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE

