/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * File Description:
 *   This code was generated by application DATATOOL
 *   using the following specifications:
 *   'pepXML.xsd'.
 *
 * ATTENTION:
 *   Don't edit or commit this file into CVS as this file will
 *   be overridden (by DATATOOL) without warning!
 * ===========================================================================
 */

// standard includes
#include <ncbi_pch.hpp>
#include <serial/serialimpl.hpp>

// generated includes
#include <algo/ms/formats/pepxml/Asapratio_contribution.hpp>
#include <algo/ms/formats/pepxml/Asapratio_lc_heavypeak.hpp>
#include <algo/ms/formats/pepxml/Asapratio_lc_lightpeak.hpp>
BEGIN_NCBI_SCOPE

BEGIN_objects_SCOPE // namespace ncbi::objects::


// generated classes

void CAsapratio_contribution_Base::C_Attlist::Reset(void)
{
    ResetRatio();
    ResetError();
    ResetCharge();
    ResetUse();
}

BEGIN_NAMED_CLASS_INFO("", CAsapratio_contribution_Base::C_Attlist)
{
    SET_INTERNAL_NAME("asapratio_contribution", "Attlist");
    SET_CLASS_MODULE("pepXML");
    ADD_NAMED_STD_MEMBER("ratio", m_Ratio)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("error", m_Error)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("charge", m_Charge)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("use", m_Use)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    info->SetRandomOrder(true);
}
END_CLASS_INFO

// constructor
CAsapratio_contribution_Base::C_Attlist::C_Attlist(void)
    : m_Ratio(0), m_Error(0), m_Charge(0), m_Use(0)
{
    memset(m_set_State,0,sizeof(m_set_State));
}

// destructor
CAsapratio_contribution_Base::C_Attlist::~C_Attlist(void)
{
}


void CAsapratio_contribution_Base::ResetAttlist(void)
{
    if ( !m_Attlist ) {
        m_Attlist.Reset(new TAttlist());
        return;
    }
    (*m_Attlist).Reset();
}

void CAsapratio_contribution_Base::SetAttlist(CAsapratio_contribution_Base::TAttlist& value)
{
    m_Attlist.Reset(&value);
}

bool CAsapratio_contribution_Base::IsSetAsapratio_lc_lightpeak(void) const
{
    return m_Asapratio_lc_lightpeak ? m_Asapratio_lc_lightpeak->IsSetAsapratio_lc_lightpeak() : false;
}

void CAsapratio_contribution_Base::ResetAsapratio_lc_lightpeak(void)
{
    if ( !m_Asapratio_lc_lightpeak ) {
        m_Asapratio_lc_lightpeak.Reset(new TAsapratio_lc_lightpeak());
        return;
    }
    (*m_Asapratio_lc_lightpeak).Reset();
}

void CAsapratio_contribution_Base::SetAsapratio_lc_lightpeak(CAsapratio_contribution_Base::TAsapratio_lc_lightpeak& value)
{
    m_Asapratio_lc_lightpeak.Reset(&value);
}

CAsapratio_contribution_Base::TAsapratio_lc_lightpeak& CAsapratio_contribution_Base::SetAsapratio_lc_lightpeak(void)
{
    if ( !m_Asapratio_lc_lightpeak ) {
        ResetAsapratio_lc_lightpeak();
    }
    m_Asapratio_lc_lightpeak->SetAsapratio_lc_lightpeak();
    return (*m_Asapratio_lc_lightpeak);
}

bool CAsapratio_contribution_Base::IsSetAsapratio_lc_heavypeak(void) const
{
    return m_Asapratio_lc_heavypeak ? m_Asapratio_lc_heavypeak->IsSetAsapratio_lc_heavypeak() : false;
}

void CAsapratio_contribution_Base::ResetAsapratio_lc_heavypeak(void)
{
    if ( !m_Asapratio_lc_heavypeak ) {
        m_Asapratio_lc_heavypeak.Reset(new TAsapratio_lc_heavypeak());
        return;
    }
    (*m_Asapratio_lc_heavypeak).Reset();
}

void CAsapratio_contribution_Base::SetAsapratio_lc_heavypeak(CAsapratio_contribution_Base::TAsapratio_lc_heavypeak& value)
{
    m_Asapratio_lc_heavypeak.Reset(&value);
}

CAsapratio_contribution_Base::TAsapratio_lc_heavypeak& CAsapratio_contribution_Base::SetAsapratio_lc_heavypeak(void)
{
    if ( !m_Asapratio_lc_heavypeak ) {
        ResetAsapratio_lc_heavypeak();
    }
    m_Asapratio_lc_heavypeak->SetAsapratio_lc_heavypeak();
    return (*m_Asapratio_lc_heavypeak);
}

void CAsapratio_contribution_Base::Reset(void)
{
    ResetAttlist();
    ResetAsapratio_lc_lightpeak();
    ResetAsapratio_lc_heavypeak();
}

BEGIN_NAMED_BASE_CLASS_INFO("asapratio_contribution", CAsapratio_contribution)
{
    SET_CLASS_MODULE("pepXML");
    SET_NAMESPACE("http://regis-web.systemsbiology.net/pepXML")->SetNsQualified(true);
    ADD_NAMED_REF_MEMBER("Attlist", m_Attlist, C_Attlist)->SetNoPrefix()->SetAttlist();
    ADD_NAMED_REF_MEMBER("asapratio_lc_lightpeak", m_Asapratio_lc_lightpeak, CAsapratio_lc_lightpeak)->SetNoPrefix();
    ADD_NAMED_REF_MEMBER("asapratio_lc_heavypeak", m_Asapratio_lc_heavypeak, CAsapratio_lc_heavypeak)->SetNoPrefix();
    info->RandomOrder();
}
END_CLASS_INFO

// constructor
CAsapratio_contribution_Base::CAsapratio_contribution_Base(void)
{
    memset(m_set_State,0,sizeof(m_set_State));
    if ( !IsAllocatedInPool() ) {
        ResetAttlist();
        ResetAsapratio_lc_lightpeak();
        ResetAsapratio_lc_heavypeak();
    }
}

// destructor
CAsapratio_contribution_Base::~CAsapratio_contribution_Base(void)
{
}



END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE

