/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * File Description:
 *   This code was generated by application DATATOOL
 *   using the following specifications:
 *   'pepXML.xsd'.
 *
 * ATTENTION:
 *   Don't edit or commit this file into CVS as this file will
 *   be overridden (by DATATOOL) without warning!
 * ===========================================================================
 */

// standard includes
#include <ncbi_pch.hpp>
#include <serial/serialimpl.hpp>

// generated includes
#include <algo/ms/formats/pepxml/Libra_summary.hpp>
#include <algo/ms/formats/pepxml/Fragment_masses.hpp>
#include <algo/ms/formats/pepxml/Isotopic_contributions.hpp>
BEGIN_NCBI_SCOPE

BEGIN_objects_SCOPE // namespace ncbi::objects::


// generated classes

void CLibra_summary_Base::C_Attlist::ResetChannel_code(void)
{
    m_Channel_code.erase();
    m_set_State[0] &= ~0x300;
}

void CLibra_summary_Base::C_Attlist::Reset(void)
{
    ResetMass_tolerance();
    ResetCentroiding_preference();
    ResetNormalization();
    ResetOutput_type();
    ResetChannel_code();
}

BEGIN_NAMED_CLASS_INFO("", CLibra_summary_Base::C_Attlist)
{
    SET_INTERNAL_NAME("libra_summary", "Attlist");
    SET_CLASS_MODULE("pepXML");
    ADD_NAMED_STD_MEMBER("mass_tolerance", m_Mass_tolerance)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("centroiding_preference", m_Centroiding_preference)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("normalization", m_Normalization)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("output_type", m_Output_type)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("channel_code", m_Channel_code)->SetOptional()->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    info->SetRandomOrder(true);
}
END_CLASS_INFO

// constructor
CLibra_summary_Base::C_Attlist::C_Attlist(void)
    : m_Mass_tolerance(0), m_Centroiding_preference(0), m_Normalization(0), m_Output_type(0)
{
    memset(m_set_State,0,sizeof(m_set_State));
}

// destructor
CLibra_summary_Base::C_Attlist::~C_Attlist(void)
{
}


void CLibra_summary_Base::ResetAttlist(void)
{
    if ( !m_Attlist ) {
        m_Attlist.Reset(new TAttlist());
        return;
    }
    (*m_Attlist).Reset();
}

void CLibra_summary_Base::SetAttlist(CLibra_summary_Base::TAttlist& value)
{
    m_Attlist.Reset(&value);
}

void CLibra_summary_Base::ResetFragment_masses(void)
{
    m_Fragment_masses.clear();
    m_set_State[0] &= ~0xc;
}

void CLibra_summary_Base::ResetIsotopic_contributions(void)
{
    m_Isotopic_contributions.Reset();
}

void CLibra_summary_Base::SetIsotopic_contributions(CLibra_summary_Base::TIsotopic_contributions& value)
{
    m_Isotopic_contributions.Reset(&value);
}

CLibra_summary_Base::TIsotopic_contributions& CLibra_summary_Base::SetIsotopic_contributions(void)
{
    if ( !m_Isotopic_contributions )
        m_Isotopic_contributions.Reset(new ncbi::objects::CIsotopic_contributions());
    return (*m_Isotopic_contributions);
}

void CLibra_summary_Base::Reset(void)
{
    ResetAttlist();
    ResetFragment_masses();
    ResetIsotopic_contributions();
}

BEGIN_NAMED_BASE_CLASS_INFO("libra_summary", CLibra_summary)
{
    SET_CLASS_MODULE("pepXML");
    SET_NAMESPACE("http://regis-web.systemsbiology.net/pepXML")->SetNsQualified(true);
    ADD_NAMED_REF_MEMBER("Attlist", m_Attlist, C_Attlist)->SetNoPrefix()->SetAttlist();
    ADD_NAMED_MEMBER("fragment_masses", m_Fragment_masses, STL_list, (STL_CRef, (CLASS, (CFragment_masses))))->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_REF_MEMBER("isotopic_contributions", m_Isotopic_contributions, CIsotopic_contributions)->SetOptional()->SetNoPrefix();
    info->RandomOrder();
}
END_CLASS_INFO

// constructor
CLibra_summary_Base::CLibra_summary_Base(void)
{
    memset(m_set_State,0,sizeof(m_set_State));
    if ( !IsAllocatedInPool() ) {
        ResetAttlist();
    }
}

// destructor
CLibra_summary_Base::~CLibra_summary_Base(void)
{
}



END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE

