/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 */

/// @file Aminoacid_modification.hpp
/// User-defined methods of the data storage class.
///
/// This file was originally generated by application DATATOOL
/// using the following specifications:
/// 'pepXML.xsd'.
///
/// New methods or data members can be added to it if needed.
/// See also: Aminoacid_modification_.hpp


#ifndef ALGO_MS_FORMATS_PEPXML_AMINOACID_MODIFICATION_HPP
#define ALGO_MS_FORMATS_PEPXML_AMINOACID_MODIFICATION_HPP


// generated includes
#include <algo/ms/formats/pepxml/Aminoacid_modification_.hpp>

// generated classes

BEGIN_NCBI_SCOPE

BEGIN_objects_SCOPE // namespace ncbi::objects::

/////////////////////////////////////////////////////////////////////////////
class NCBI_PEPXML_EXPORT CAminoacid_modification : public CAminoacid_modification_Base
{
    typedef CAminoacid_modification_Base Tparent;
public:
    // constructor
    CAminoacid_modification(void);
    // destructor
    ~CAminoacid_modification(void);

private:
    // Prohibit copy constructor and assignment operator
    CAminoacid_modification(const CAminoacid_modification& value);
    CAminoacid_modification& operator=(const CAminoacid_modification& value);

};

/////////////////// CAminoacid_modification inline methods

// constructor
inline
CAminoacid_modification::CAminoacid_modification(void)
{
}


/////////////////// end of CAminoacid_modification inline methods


END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE


#endif // ALGO_MS_FORMATS_PEPXML_AMINOACID_MODIFICATION_HPP
/* Original file checksum: lines: 86, chars: 2689, CRC32: 6b31de23 */
