/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 */

/// @file Isotopic_contributions_.hpp
/// Data storage class.
///
/// This file was generated by application DATATOOL
/// using the following specifications:
/// 'pepXML.xsd'.
///
/// ATTENTION:
///   Don't edit or commit this file into CVS as this file will
///   be overridden (by DATATOOL) without warning!

#ifndef ALGO_MS_FORMATS_PEPXML_ISOTOPIC_CONTRIBUTIONS_BASE_HPP
#define ALGO_MS_FORMATS_PEPXML_ISOTOPIC_CONTRIBUTIONS_BASE_HPP

// standard includes
#include <serial/serialbase.hpp>

// generated includes
#include <list>

BEGIN_NCBI_SCOPE

#ifndef BEGIN_objects_SCOPE
#  define BEGIN_objects_SCOPE BEGIN_SCOPE(objects)
#  define END_objects_SCOPE END_SCOPE(objects)
#endif
BEGIN_objects_SCOPE // namespace ncbi::objects::


// forward declarations
class CContributing_channel;


// generated classes

/////////////////////////////////////////////////////////////////////////////
///isotopic contributions from one channel to others 
class NCBI_PEPXML_EXPORT CIsotopic_contributions_Base : public CSerialObject
{
    typedef CSerialObject Tparent;
public:
    // constructor
    CIsotopic_contributions_Base(void);
    // destructor
    virtual ~CIsotopic_contributions_Base(void);

    // type info
    DECLARE_INTERNAL_TYPE_INFO();

    // types
    typedef list< CRef< CContributing_channel > > TContributing_channel;

    // getters
    // setters

    /// mandatory
    /// typedef list< CRef< CContributing_channel > > TContributing_channel
    ///  Check whether the Contributing_channel data member has been assigned a value.
    bool IsSetContributing_channel(void) const;
    /// Check whether it is safe or not to call GetContributing_channel method.
    bool CanGetContributing_channel(void) const;
    void ResetContributing_channel(void);
    const TContributing_channel& GetContributing_channel(void) const;
    TContributing_channel& SetContributing_channel(void);

    /// Reset the whole object
    virtual void Reset(void);


private:
    // Prohibit copy constructor and assignment operator
    CIsotopic_contributions_Base(const CIsotopic_contributions_Base&);
    CIsotopic_contributions_Base& operator=(const CIsotopic_contributions_Base&);

    // data
    Uint4 m_set_State[1];
    list< CRef< CContributing_channel > > m_Contributing_channel;
};






///////////////////////////////////////////////////////////
///////////////////// inline methods //////////////////////
///////////////////////////////////////////////////////////
inline
bool CIsotopic_contributions_Base::IsSetContributing_channel(void) const
{
    return ((m_set_State[0] & 0x3) != 0);
}

inline
bool CIsotopic_contributions_Base::CanGetContributing_channel(void) const
{
    return true;
}

inline
const CIsotopic_contributions_Base::TContributing_channel& CIsotopic_contributions_Base::GetContributing_channel(void) const
{
    return m_Contributing_channel;
}

inline
CIsotopic_contributions_Base::TContributing_channel& CIsotopic_contributions_Base::SetContributing_channel(void)
{
    m_set_State[0] |= 0x1;
    return m_Contributing_channel;
}

///////////////////////////////////////////////////////////
////////////////// end of inline methods //////////////////
///////////////////////////////////////////////////////////





END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE


#endif // ALGO_MS_FORMATS_PEPXML_ISOTOPIC_CONTRIBUTIONS_BASE_HPP
