/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 */

/// @file Mixturemodel_distribution_.hpp
/// Data storage class.
///
/// This file was generated by application DATATOOL
/// using the following specifications:
/// 'pepXML.xsd'.
///
/// ATTENTION:
///   Don't edit or commit this file into CVS as this file will
///   be overridden (by DATATOOL) without warning!

#ifndef ALGO_MS_FORMATS_PEPXML_MIXTUREMODEL_DISTRIBUTION_BASE_HPP
#define ALGO_MS_FORMATS_PEPXML_MIXTUREMODEL_DISTRIBUTION_BASE_HPP

// standard includes
#include <serial/serialbase.hpp>

// generated includes
#include <string>

BEGIN_NCBI_SCOPE

#ifndef BEGIN_objects_SCOPE
#  define BEGIN_objects_SCOPE BEGIN_SCOPE(objects)
#  define END_objects_SCOPE END_SCOPE(objects)
#endif
BEGIN_objects_SCOPE // namespace ncbi::objects::


// forward declarations
class CNegmodel_distribution;
class CPosmodel_distribution;


// generated classes

/////////////////////////////////////////////////////////////////////////////
class NCBI_PEPXML_EXPORT CMixturemodel_distribution_Base : public CSerialObject
{
    typedef CSerialObject Tparent;
public:
    // constructor
    CMixturemodel_distribution_Base(void);
    // destructor
    virtual ~CMixturemodel_distribution_Base(void);

    // type info
    DECLARE_INTERNAL_TYPE_INFO();

    /////////////////////////////////////////////////////////////////////////////
    class NCBI_PEPXML_EXPORT C_Attlist : public CSerialObject
    {
        typedef CSerialObject Tparent;
    public:
        // constructor
        C_Attlist(void);
        // destructor
        ~C_Attlist(void);
    
        // type info
        DECLARE_INTERNAL_TYPE_INFO();
    
        // types
        typedef string TName;
    
        // getters
        // setters
    
        /// mandatory
        /// typedef string TName
        ///  Check whether the Name data member has been assigned a value.
        bool IsSetName(void) const;
        /// Check whether it is safe or not to call GetName method.
        bool CanGetName(void) const;
        void ResetName(void);
        const TName& GetName(void) const;
        void SetName(const TName& value);
        TName& SetName(void);
    
        /// Reset the whole object
        void Reset(void);
    
    
    private:
        // Prohibit copy constructor and assignment operator
        C_Attlist(const C_Attlist&);
        C_Attlist& operator=(const C_Attlist&);
    
        // data
        Uint4 m_set_State[1];
        string m_Name;
    };
    // types
    typedef C_Attlist TAttlist;
    typedef CPosmodel_distribution TPosmodel_distribution;
    typedef CNegmodel_distribution TNegmodel_distribution;

    // getters
    // setters

    /// mandatory
    /// typedef C_Attlist TAttlist
    ///  Check whether the Attlist data member has been assigned a value.
    bool IsSetAttlist(void) const;
    /// Check whether it is safe or not to call GetAttlist method.
    bool CanGetAttlist(void) const;
    void ResetAttlist(void);
    const TAttlist& GetAttlist(void) const;
    void SetAttlist(TAttlist& value);
    TAttlist& SetAttlist(void);

    /// mandatory
    /// typedef CPosmodel_distribution TPosmodel_distribution
    ///  Check whether the Posmodel_distribution data member has been assigned a value.
    bool IsSetPosmodel_distribution(void) const;
    /// Check whether it is safe or not to call GetPosmodel_distribution method.
    bool CanGetPosmodel_distribution(void) const;
    void ResetPosmodel_distribution(void);
    const TPosmodel_distribution& GetPosmodel_distribution(void) const;
    void SetPosmodel_distribution(TPosmodel_distribution& value);
    TPosmodel_distribution& SetPosmodel_distribution(void);

    /// mandatory
    /// typedef CNegmodel_distribution TNegmodel_distribution
    ///  Check whether the Negmodel_distribution data member has been assigned a value.
    bool IsSetNegmodel_distribution(void) const;
    /// Check whether it is safe or not to call GetNegmodel_distribution method.
    bool CanGetNegmodel_distribution(void) const;
    void ResetNegmodel_distribution(void);
    const TNegmodel_distribution& GetNegmodel_distribution(void) const;
    void SetNegmodel_distribution(TNegmodel_distribution& value);
    TNegmodel_distribution& SetNegmodel_distribution(void);

    /// Reset the whole object
    virtual void Reset(void);


private:
    // Prohibit copy constructor and assignment operator
    CMixturemodel_distribution_Base(const CMixturemodel_distribution_Base&);
    CMixturemodel_distribution_Base& operator=(const CMixturemodel_distribution_Base&);

    // data
    Uint4 m_set_State[1];
    CRef< TAttlist > m_Attlist;
    CRef< TPosmodel_distribution > m_Posmodel_distribution;
    CRef< TNegmodel_distribution > m_Negmodel_distribution;
};






///////////////////////////////////////////////////////////
///////////////////// inline methods //////////////////////
///////////////////////////////////////////////////////////
inline
bool CMixturemodel_distribution_Base::C_Attlist::IsSetName(void) const
{
    return ((m_set_State[0] & 0x3) != 0);
}

inline
bool CMixturemodel_distribution_Base::C_Attlist::CanGetName(void) const
{
    return IsSetName();
}

inline
const CMixturemodel_distribution_Base::C_Attlist::TName& CMixturemodel_distribution_Base::C_Attlist::GetName(void) const
{
    if (!CanGetName()) {
        ThrowUnassigned(0);
    }
    return m_Name;
}

inline
void CMixturemodel_distribution_Base::C_Attlist::SetName(const CMixturemodel_distribution_Base::C_Attlist::TName& value)
{
    m_Name = value;
    m_set_State[0] |= 0x3;
}

inline
CMixturemodel_distribution_Base::C_Attlist::TName& CMixturemodel_distribution_Base::C_Attlist::SetName(void)
{
#ifdef _DEBUG
    if (!IsSetName()) {
        m_Name = UnassignedString();
    }
#endif
    m_set_State[0] |= 0x1;
    return m_Name;
}

inline
bool CMixturemodel_distribution_Base::IsSetAttlist(void) const
{
    return m_Attlist.NotEmpty();
}

inline
bool CMixturemodel_distribution_Base::CanGetAttlist(void) const
{
    return true;
}

inline
const CMixturemodel_distribution_Base::TAttlist& CMixturemodel_distribution_Base::GetAttlist(void) const
{
    if ( !m_Attlist ) {
        const_cast<CMixturemodel_distribution_Base*>(this)->ResetAttlist();
    }
    return (*m_Attlist);
}

inline
CMixturemodel_distribution_Base::TAttlist& CMixturemodel_distribution_Base::SetAttlist(void)
{
    if ( !m_Attlist ) {
        ResetAttlist();
    }
    return (*m_Attlist);
}

inline
bool CMixturemodel_distribution_Base::IsSetPosmodel_distribution(void) const
{
    return m_Posmodel_distribution.NotEmpty();
}

inline
bool CMixturemodel_distribution_Base::CanGetPosmodel_distribution(void) const
{
    return true;
}

inline
const CMixturemodel_distribution_Base::TPosmodel_distribution& CMixturemodel_distribution_Base::GetPosmodel_distribution(void) const
{
    if ( !m_Posmodel_distribution ) {
        const_cast<CMixturemodel_distribution_Base*>(this)->ResetPosmodel_distribution();
    }
    return (*m_Posmodel_distribution);
}

inline
CMixturemodel_distribution_Base::TPosmodel_distribution& CMixturemodel_distribution_Base::SetPosmodel_distribution(void)
{
    if ( !m_Posmodel_distribution ) {
        ResetPosmodel_distribution();
    }
    return (*m_Posmodel_distribution);
}

inline
bool CMixturemodel_distribution_Base::IsSetNegmodel_distribution(void) const
{
    return m_Negmodel_distribution.NotEmpty();
}

inline
bool CMixturemodel_distribution_Base::CanGetNegmodel_distribution(void) const
{
    return true;
}

inline
const CMixturemodel_distribution_Base::TNegmodel_distribution& CMixturemodel_distribution_Base::GetNegmodel_distribution(void) const
{
    if ( !m_Negmodel_distribution ) {
        const_cast<CMixturemodel_distribution_Base*>(this)->ResetNegmodel_distribution();
    }
    return (*m_Negmodel_distribution);
}

inline
CMixturemodel_distribution_Base::TNegmodel_distribution& CMixturemodel_distribution_Base::SetNegmodel_distribution(void)
{
    if ( !m_Negmodel_distribution ) {
        ResetNegmodel_distribution();
    }
    return (*m_Negmodel_distribution);
}

///////////////////////////////////////////////////////////
////////////////// end of inline methods //////////////////
///////////////////////////////////////////////////////////





END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE


#endif // ALGO_MS_FORMATS_PEPXML_MIXTUREMODEL_DISTRIBUTION_BASE_HPP
