#include <algo/ms/formats/pepxml/Affected_channel.hpp>
#include <algo/ms/formats/pepxml/Alternative_protein.hpp>
#include <algo/ms/formats/pepxml/Aminoacid_modification.hpp>
#include <algo/ms/formats/pepxml/Analysis_result.hpp>
#include <algo/ms/formats/pepxml/Analysis_summary.hpp>
#include <algo/ms/formats/pepxml/Analysis_timestamp.hpp>
#include <algo/ms/formats/pepxml/Asapratio_contribution.hpp>
#include <algo/ms/formats/pepxml/Asapratio_lc_heavypeak.hpp>
#include <algo/ms/formats/pepxml/Asapratio_lc_lightpeak.hpp>
#include <algo/ms/formats/pepxml/Asapratio_peptide_data.hpp>
#include <algo/ms/formats/pepxml/Asapratio_result.hpp>
#include <algo/ms/formats/pepxml/Asapratio_summary.hpp>
#include <algo/ms/formats/pepxml/Asapratio_timestamp.hpp>
#include <algo/ms/formats/pepxml/Contributing_channel.hpp>
#include <algo/ms/formats/pepxml/Data_filter.hpp>
#include <algo/ms/formats/pepxml/Database_refresh_timestamp.hpp>
#include <algo/ms/formats/pepxml/Dataset_derivation.hpp>
#include <algo/ms/formats/pepxml/Distribution_point.hpp>
#include <algo/ms/formats/pepxml/Enzymatic_search_constrain.hpp>
#include <algo/ms/formats/pepxml/Error_point.hpp>
#include <algo/ms/formats/pepxml/Fragment_masses.hpp>
#include <algo/ms/formats/pepxml/Inputfile.hpp>
#include <algo/ms/formats/pepxml/Intensity.hpp>
#include <algo/ms/formats/pepxml/Interact_summary.hpp>
#include <algo/ms/formats/pepxml/Isotopic_contributions.hpp>
#include <algo/ms/formats/pepxml/Libra_result.hpp>
#include <algo/ms/formats/pepxml/Libra_summary.hpp>
#include <algo/ms/formats/pepxml/Mixture_model.hpp>
#include <algo/ms/formats/pepxml/Mixturemodel_distribution.hpp>
#include <algo/ms/formats/pepxml/Mod_aminoacid_mass.hpp>
#include <algo/ms/formats/pepxml/Modification_info.hpp>
#include <algo/ms/formats/pepxml/Msms_pipeline_analysis.hpp>
#include <algo/ms/formats/pepxml/Msms_run_summary.hpp>
#include <algo/ms/formats/pepxml/Negmodel_distribution.hpp>
#include <algo/ms/formats/pepxml/Parameter.hpp>
#include <algo/ms/formats/pepxml/Peptideprophet_result.hpp>
#include <algo/ms/formats/pepxml/Peptideprophet_summary.hpp>
#include <algo/ms/formats/pepxml/Posmodel_distribution.hpp>
#include <algo/ms/formats/pepxml/Roc_data_point.hpp>
#include <algo/ms/formats/pepxml/Sample_enzyme.hpp>
#include <algo/ms/formats/pepxml/Search_database.hpp>
#include <algo/ms/formats/pepxml/Search_hit.hpp>
#include <algo/ms/formats/pepxml/Search_result.hpp>
#include <algo/ms/formats/pepxml/Search_score.hpp>
#include <algo/ms/formats/pepxml/Search_score_summary.hpp>
#include <algo/ms/formats/pepxml/Search_summary.hpp>
#include <algo/ms/formats/pepxml/Sequence_search_constraint.hpp>
#include <algo/ms/formats/pepxml/Specificity.hpp>
#include <algo/ms/formats/pepxml/Spectrum_query.hpp>
#include <algo/ms/formats/pepxml/Terminal_modification.hpp>
#include <algo/ms/formats/pepxml/Xpressratio_result.hpp>
#include <algo/ms/formats/pepxml/Xpressratio_summary.hpp>
#include <algo/ms/formats/pepxml/Xpressratio_timestamp.hpp>
#include <algo/ms/formats/pepxml/pepXML_module.hpp>
