/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 */

/// @file Posmodel_distribution_.hpp
/// Data storage class.
///
/// This file was generated by application DATATOOL
/// using the following specifications:
/// 'pepXML.xsd'.
///
/// ATTENTION:
///   Don't edit or commit this file into CVS as this file will
///   be overridden (by DATATOOL) without warning!

#ifndef ALGO_MS_FORMATS_PEPXML_POSMODEL_DISTRIBUTION_BASE_HPP
#define ALGO_MS_FORMATS_PEPXML_POSMODEL_DISTRIBUTION_BASE_HPP

// standard includes
#include <serial/serialbase.hpp>

// generated includes
#include <list>

BEGIN_NCBI_SCOPE

#ifndef BEGIN_objects_SCOPE
#  define BEGIN_objects_SCOPE BEGIN_SCOPE(objects)
#  define END_objects_SCOPE END_SCOPE(objects)
#endif
BEGIN_objects_SCOPE // namespace ncbi::objects::


// forward declarations
class CParameter;


// generated classes

/////////////////////////////////////////////////////////////////////////////
class NCBI_PEPXML_EXPORT CPosmodel_distribution_Base : public CSerialObject
{
    typedef CSerialObject Tparent;
public:
    // constructor
    CPosmodel_distribution_Base(void);
    // destructor
    virtual ~CPosmodel_distribution_Base(void);

    // type info
    DECLARE_INTERNAL_TYPE_INFO();

    /////////////////////////////////////////////////////////////////////////////
    class NCBI_PEPXML_EXPORT C_Attlist : public CSerialObject
    {
        typedef CSerialObject Tparent;
    public:
        // constructor
        C_Attlist(void);
        // destructor
        ~C_Attlist(void);
    
        // type info
        DECLARE_INTERNAL_TYPE_INFO();
    
        enum EAttlist_type {
            eAttlist_type_discrete     = 1,
            eAttlist_type_gaussian     = 2,
            eAttlist_type_extremevalue = 3,
            eAttlist_type_gamma        = 4,
            eAttlist_type_evd          = 5
        };
        
        /// Access to EAttlist_type's attributes (values, names) as defined in spec
        static const NCBI_NS_NCBI::CEnumeratedTypeValues* ENUM_METHOD_NAME(EAttlist_type)(void);
        
        // types
        typedef EAttlist_type TType;
    
        // getters
        // setters
    
        /// optional
        /// typedef EAttlist_type TType
        ///  Check whether the Type data member has been assigned a value.
        bool IsSetType(void) const;
        /// Check whether it is safe or not to call GetType method.
        bool CanGetType(void) const;
        void ResetType(void);
        TType GetType(void) const;
        void SetType(TType value);
        TType& SetType(void);
    
        /// Reset the whole object
        void Reset(void);
    
    
    private:
        // Prohibit copy constructor and assignment operator
        C_Attlist(const C_Attlist&);
        C_Attlist& operator=(const C_Attlist&);
    
        // data
        Uint4 m_set_State[1];
        EAttlist_type m_Type;
    };
    // types
    typedef C_Attlist TAttlist;
    typedef list< CRef< CParameter > > TParameter;

    // getters
    // setters

    /// mandatory
    /// typedef C_Attlist TAttlist
    ///  Check whether the Attlist data member has been assigned a value.
    bool IsSetAttlist(void) const;
    /// Check whether it is safe or not to call GetAttlist method.
    bool CanGetAttlist(void) const;
    void ResetAttlist(void);
    const TAttlist& GetAttlist(void) const;
    void SetAttlist(TAttlist& value);
    TAttlist& SetAttlist(void);

    /// mandatory
    /// typedef list< CRef< CParameter > > TParameter
    ///  Check whether the Parameter data member has been assigned a value.
    bool IsSetParameter(void) const;
    /// Check whether it is safe or not to call GetParameter method.
    bool CanGetParameter(void) const;
    void ResetParameter(void);
    const TParameter& GetParameter(void) const;
    TParameter& SetParameter(void);

    /// Reset the whole object
    virtual void Reset(void);


private:
    // Prohibit copy constructor and assignment operator
    CPosmodel_distribution_Base(const CPosmodel_distribution_Base&);
    CPosmodel_distribution_Base& operator=(const CPosmodel_distribution_Base&);

    // data
    Uint4 m_set_State[1];
    CRef< TAttlist > m_Attlist;
    list< CRef< CParameter > > m_Parameter;
};






///////////////////////////////////////////////////////////
///////////////////// inline methods //////////////////////
///////////////////////////////////////////////////////////
inline
bool CPosmodel_distribution_Base::C_Attlist::IsSetType(void) const
{
    return ((m_set_State[0] & 0x3) != 0);
}

inline
bool CPosmodel_distribution_Base::C_Attlist::CanGetType(void) const
{
    return IsSetType();
}

inline
void CPosmodel_distribution_Base::C_Attlist::ResetType(void)
{
    m_Type = (EAttlist_type)(0);
    m_set_State[0] &= ~0x3;
}

inline
CPosmodel_distribution_Base::C_Attlist::TType CPosmodel_distribution_Base::C_Attlist::GetType(void) const
{
    if (!CanGetType()) {
        ThrowUnassigned(0);
    }
    return m_Type;
}

inline
void CPosmodel_distribution_Base::C_Attlist::SetType(CPosmodel_distribution_Base::C_Attlist::TType value)
{
    m_Type = value;
    m_set_State[0] |= 0x3;
}

inline
CPosmodel_distribution_Base::C_Attlist::TType& CPosmodel_distribution_Base::C_Attlist::SetType(void)
{
#ifdef _DEBUG
    if (!IsSetType()) {
        memset(&m_Type,UnassignedByte(),sizeof(m_Type));
    }
#endif
    m_set_State[0] |= 0x1;
    return m_Type;
}

inline
bool CPosmodel_distribution_Base::IsSetAttlist(void) const
{
    return m_Attlist.NotEmpty();
}

inline
bool CPosmodel_distribution_Base::CanGetAttlist(void) const
{
    return true;
}

inline
const CPosmodel_distribution_Base::TAttlist& CPosmodel_distribution_Base::GetAttlist(void) const
{
    if ( !m_Attlist ) {
        const_cast<CPosmodel_distribution_Base*>(this)->ResetAttlist();
    }
    return (*m_Attlist);
}

inline
CPosmodel_distribution_Base::TAttlist& CPosmodel_distribution_Base::SetAttlist(void)
{
    if ( !m_Attlist ) {
        ResetAttlist();
    }
    return (*m_Attlist);
}

inline
bool CPosmodel_distribution_Base::IsSetParameter(void) const
{
    return ((m_set_State[0] & 0xc) != 0);
}

inline
bool CPosmodel_distribution_Base::CanGetParameter(void) const
{
    return true;
}

inline
const CPosmodel_distribution_Base::TParameter& CPosmodel_distribution_Base::GetParameter(void) const
{
    return m_Parameter;
}

inline
CPosmodel_distribution_Base::TParameter& CPosmodel_distribution_Base::SetParameter(void)
{
    m_set_State[0] |= 0x4;
    return m_Parameter;
}

///////////////////////////////////////////////////////////
////////////////// end of inline methods //////////////////
///////////////////////////////////////////////////////////





END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE


#endif // ALGO_MS_FORMATS_PEPXML_POSMODEL_DISTRIBUTION_BASE_HPP
