/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 */

/// @file VersionStruct_.hpp
/// Data storage class.
///
/// This file was generated by application DATATOOL
/// using the following specifications:
/// 'soap_dataobj.xsd'.
///
/// ATTENTION:
///   Don't edit or commit this file into CVS as this file will
///   be overridden (by DATATOOL) without warning!

#ifndef SAMPLE_APP_SOAP_VERSIONSTRUCT_BASE_HPP
#define SAMPLE_APP_SOAP_VERSIONSTRUCT_BASE_HPP

// standard includes
#include <serial/serialbase.hpp>

// generated includes
#include <string>

BEGIN_NCBI_SCOPE

#ifndef BEGIN_objects_SCOPE
#  define BEGIN_objects_SCOPE BEGIN_SCOPE(objects)
#  define END_objects_SCOPE END_SCOPE(objects)
#endif
BEGIN_objects_SCOPE // namespace ncbi::objects::


// generated classes

/////////////////////////////////////////////////////////////////////////////
class CVersionStruct_Base : public CSerialObject
{
    typedef CSerialObject Tparent;
public:
    // constructor
    CVersionStruct_Base(void);
    // destructor
    virtual ~CVersionStruct_Base(void);

    // type info
    DECLARE_INTERNAL_TYPE_INFO();

    // types
    typedef int TMajor;
    typedef int TMinor;
    typedef string TClientID;

    // getters
    // setters

    /// mandatory
    /// typedef int TMajor
    ///  Check whether the Major data member has been assigned a value.
    bool IsSetMajor(void) const;
    /// Check whether it is safe or not to call GetMajor method.
    bool CanGetMajor(void) const;
    void ResetMajor(void);
    TMajor GetMajor(void) const;
    void SetMajor(TMajor value);
    TMajor& SetMajor(void);

    /// mandatory
    /// typedef int TMinor
    ///  Check whether the Minor data member has been assigned a value.
    bool IsSetMinor(void) const;
    /// Check whether it is safe or not to call GetMinor method.
    bool CanGetMinor(void) const;
    void ResetMinor(void);
    TMinor GetMinor(void) const;
    void SetMinor(TMinor value);
    TMinor& SetMinor(void);

    /// mandatory
    /// typedef string TClientID
    ///  Check whether the ClientID data member has been assigned a value.
    bool IsSetClientID(void) const;
    /// Check whether it is safe or not to call GetClientID method.
    bool CanGetClientID(void) const;
    void ResetClientID(void);
    const TClientID& GetClientID(void) const;
    void SetClientID(const TClientID& value);
    TClientID& SetClientID(void);

    /// Reset the whole object
    virtual void Reset(void);


private:
    // Prohibit copy constructor and assignment operator
    CVersionStruct_Base(const CVersionStruct_Base&);
    CVersionStruct_Base& operator=(const CVersionStruct_Base&);

    // data
    Uint4 m_set_State[1];
    int m_Major;
    int m_Minor;
    string m_ClientID;
};






///////////////////////////////////////////////////////////
///////////////////// inline methods //////////////////////
///////////////////////////////////////////////////////////
inline
bool CVersionStruct_Base::IsSetMajor(void) const
{
    return ((m_set_State[0] & 0x3) != 0);
}

inline
bool CVersionStruct_Base::CanGetMajor(void) const
{
    return IsSetMajor();
}

inline
void CVersionStruct_Base::ResetMajor(void)
{
    m_Major = 0;
    m_set_State[0] &= ~0x3;
}

inline
CVersionStruct_Base::TMajor CVersionStruct_Base::GetMajor(void) const
{
    if (!CanGetMajor()) {
        ThrowUnassigned(0);
    }
    return m_Major;
}

inline
void CVersionStruct_Base::SetMajor(CVersionStruct_Base::TMajor value)
{
    m_Major = value;
    m_set_State[0] |= 0x3;
}

inline
CVersionStruct_Base::TMajor& CVersionStruct_Base::SetMajor(void)
{
#ifdef _DEBUG
    if (!IsSetMajor()) {
        memset(&m_Major,UnassignedByte(),sizeof(m_Major));
    }
#endif
    m_set_State[0] |= 0x1;
    return m_Major;
}

inline
bool CVersionStruct_Base::IsSetMinor(void) const
{
    return ((m_set_State[0] & 0xc) != 0);
}

inline
bool CVersionStruct_Base::CanGetMinor(void) const
{
    return IsSetMinor();
}

inline
void CVersionStruct_Base::ResetMinor(void)
{
    m_Minor = 0;
    m_set_State[0] &= ~0xc;
}

inline
CVersionStruct_Base::TMinor CVersionStruct_Base::GetMinor(void) const
{
    if (!CanGetMinor()) {
        ThrowUnassigned(1);
    }
    return m_Minor;
}

inline
void CVersionStruct_Base::SetMinor(CVersionStruct_Base::TMinor value)
{
    m_Minor = value;
    m_set_State[0] |= 0xc;
}

inline
CVersionStruct_Base::TMinor& CVersionStruct_Base::SetMinor(void)
{
#ifdef _DEBUG
    if (!IsSetMinor()) {
        memset(&m_Minor,UnassignedByte(),sizeof(m_Minor));
    }
#endif
    m_set_State[0] |= 0x4;
    return m_Minor;
}

inline
bool CVersionStruct_Base::IsSetClientID(void) const
{
    return ((m_set_State[0] & 0x30) != 0);
}

inline
bool CVersionStruct_Base::CanGetClientID(void) const
{
    return IsSetClientID();
}

inline
const CVersionStruct_Base::TClientID& CVersionStruct_Base::GetClientID(void) const
{
    if (!CanGetClientID()) {
        ThrowUnassigned(2);
    }
    return m_ClientID;
}

inline
void CVersionStruct_Base::SetClientID(const CVersionStruct_Base::TClientID& value)
{
    m_ClientID = value;
    m_set_State[0] |= 0x30;
}

inline
CVersionStruct_Base::TClientID& CVersionStruct_Base::SetClientID(void)
{
#ifdef _DEBUG
    if (!IsSetClientID()) {
        m_ClientID = UnassignedString();
    }
#endif
    m_set_State[0] |= 0x10;
    return m_ClientID;
}

///////////////////////////////////////////////////////////
////////////////// end of inline methods //////////////////
///////////////////////////////////////////////////////////





END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE


#endif // SAMPLE_APP_SOAP_VERSIONSTRUCT_BASE_HPP
