/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 */

/// @file Query_Search.hpp
/// User-defined methods of the data storage class.
///
/// This file was originally generated by application DATATOOL
/// using the following specifications:
/// 'we_cpp.asn'.
///
/// New methods or data members can be added to it if needed.
/// See also: Query_Search_.hpp


#ifndef SERIAL_TEST_QUERY_SEARCH_HPP
#define SERIAL_TEST_QUERY_SEARCH_HPP


// generated includes
#include <serial/test/Query_Search_.hpp>

// generated classes

BEGIN_NCBI_SCOPE

BEGIN_objects_SCOPE // namespace ncbi::objects::

/////////////////////////////////////////////////////////////////////////////
class CQuery_Search : public CQuery_Search_Base
{
    typedef CQuery_Search_Base Tparent;
public:
    // constructor
    CQuery_Search(void);
    // destructor
    ~CQuery_Search(void);

private:
    // Prohibit copy constructor and assignment operator
    CQuery_Search(const CQuery_Search& value);
    CQuery_Search& operator=(const CQuery_Search& value);

};

/////////////////// CQuery_Search inline methods

// constructor
inline
CQuery_Search::CQuery_Search(void)
{
}


/////////////////// end of CQuery_Search inline methods


END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE


#endif // SERIAL_TEST_QUERY_SEARCH_HPP
/* Original file checksum: lines: 86, chars: 2436, CRC32: cd86661b */
