/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * File Description:
 *   This code was generated by application DATATOOL
 *   using the following specifications:
 *   'esearch.dtd'.
 *
 * ATTENTION:
 *   Don't edit or commit this file into CVS as this file will
 *   be overridden (by DATATOOL) without warning!
 * ===========================================================================
 */

// standard includes
#include <ncbi_pch.hpp>
#include <serial/serialimpl.hpp>

// generated includes
#include <objtools/eutils/esearch/Translation.hpp>
BEGIN_esearch_SCOPE // namespace esearch::


// generated classes

void CTranslation_Base::ResetFrom(void)
{
    m_From.erase();
    m_set_State[0] &= ~0x3;
}

void CTranslation_Base::ResetTo(void)
{
    m_To.erase();
    m_set_State[0] &= ~0xc;
}

void CTranslation_Base::Reset(void)
{
    ResetFrom();
    ResetTo();
}

BEGIN_NAMED_BASE_CLASS_INFO("Translation", CTranslation)
{
    SET_CLASS_MODULE("esearch");
    ADD_NAMED_STD_MEMBER("From", m_From)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    ADD_NAMED_STD_MEMBER("To", m_To)->SetSetFlag(MEMBER_PTR(m_set_State[0]))->SetNoPrefix();
    info->RandomOrder();
}
END_CLASS_INFO

// constructor
CTranslation_Base::CTranslation_Base(void)
{
    memset(m_set_State,0,sizeof(m_set_State));
}

// destructor
CTranslation_Base::~CTranslation_Base(void)
{
}



END_esearch_SCOPE // namespace esearch::

