/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 */

/// @file InvalidIdList.hpp
/// User-defined methods of the data storage class.
///
/// This file was originally generated by application DATATOOL
/// using the following specifications:
/// 'epost.dtd'.
///
/// New methods or data members can be added to it if needed.
/// See also: InvalidIdList_.hpp


#ifndef epost__OBJTOOLS_EUTILS_EPOST_INVALIDIDLIST_HPP
#define epost__OBJTOOLS_EUTILS_EPOST_INVALIDIDLIST_HPP


// generated includes
#include <objtools/eutils/epost/InvalidIdList_.hpp>

// generated classes

BEGIN_epost_SCOPE // namespace epost::

/////////////////////////////////////////////////////////////////////////////
class NCBI_EUTILS_EXPORT CInvalidIdList : public CInvalidIdList_Base
{
    typedef CInvalidIdList_Base Tparent;
public:
    // constructor
    CInvalidIdList(void);
    // destructor
    ~CInvalidIdList(void);

private:
    // Prohibit copy constructor and assignment operator
    CInvalidIdList(const CInvalidIdList& value);
    CInvalidIdList& operator=(const CInvalidIdList& value);

};

/////////////////// CInvalidIdList inline methods

// constructor
inline
CInvalidIdList::CInvalidIdList(void)
{
}


/////////////////// end of CInvalidIdList inline methods


END_epost_SCOPE // namespace epost::


#endif // epost__OBJTOOLS_EUTILS_EPOST_INVALIDIDLIST_HPP
/* Original file checksum: lines: 82, chars: 2484, CRC32: acdadeb1 */
