/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 */

/// @file Data_set_id_uids.hpp
/// User-defined methods of the data storage class.
///
/// This file was originally generated by application DATATOOL
/// using the following specifications:
/// 'dtd_sample_lib.dtd'.
///
/// New methods or data members can be added to it if needed.
/// See also: Data_set_id_uids_.hpp


#ifndef SAMPLE_LIB_DTD_DATA_SET_ID_UIDS_HPP
#define SAMPLE_LIB_DTD_DATA_SET_ID_UIDS_HPP


// generated includes
#include <sample/lib/dtd/Data_set_id_uids_.hpp>

// generated classes

BEGIN_NCBI_SCOPE

BEGIN_objects_SCOPE // namespace ncbi::objects::

/////////////////////////////////////////////////////////////////////////////
class CData_set_id_uids : public CData_set_id_uids_Base
{
    typedef CData_set_id_uids_Base Tparent;
public:
    // constructor
    CData_set_id_uids(void);
    // destructor
    ~CData_set_id_uids(void);

private:
    // Prohibit copy constructor and assignment operator
    CData_set_id_uids(const CData_set_id_uids& value);
    CData_set_id_uids& operator=(const CData_set_id_uids& value);

};

/////////////////// CData_set_id_uids inline methods

// constructor
inline
CData_set_id_uids::CData_set_id_uids(void)
{
}


/////////////////// end of CData_set_id_uids inline methods


END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE


#endif // SAMPLE_LIB_DTD_DATA_SET_ID_UIDS_HPP
/* Original file checksum: lines: 86, chars: 2532, CRC32: b781a234 */
