/* $Id$
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 */

/// @file EHistoryResult.hpp
/// User-defined methods of the data storage class.
///
/// This file was originally generated by application DATATOOL
/// using the following specifications:
/// 'ehistory.dtd'.
///
/// New methods or data members can be added to it if needed.
/// See also: EHistoryResult_.hpp


#ifndef ehistory__OBJTOOLS_EUTILS_EHISTORY_EHISTORYRESULT_HPP
#define ehistory__OBJTOOLS_EUTILS_EHISTORY_EHISTORYRESULT_HPP


// generated includes
#include <objtools/eutils/ehistory/EHistoryResult_.hpp>

// generated classes

BEGIN_ehistory_SCOPE // namespace ehistory::

/////////////////////////////////////////////////////////////////////////////
class NCBI_EUTILS_EXPORT CEHistoryResult : public CEHistoryResult_Base
{
    typedef CEHistoryResult_Base Tparent;
public:
    // constructor
    CEHistoryResult(void);
    // destructor
    ~CEHistoryResult(void);

private:
    // Prohibit copy constructor and assignment operator
    CEHistoryResult(const CEHistoryResult& value);
    CEHistoryResult& operator=(const CEHistoryResult& value);

};

/////////////////// CEHistoryResult inline methods

// constructor
inline
CEHistoryResult::CEHistoryResult(void)
{
}


/////////////////// end of CEHistoryResult inline methods


END_ehistory_SCOPE // namespace ehistory::


#endif // ehistory__OBJTOOLS_EUTILS_EHISTORY_EHISTORYRESULT_HPP
/* Original file checksum: lines: 82, chars: 2539, CRC32: 8c357e45 */
